/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_rm_spacemousewrapper_SpaceMouse */

#ifndef _Included_com_rm_spacemousewrapper_SpaceMouse
#define _Included_com_rm_spacemousewrapper_SpaceMouse
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_rm_spacemousewrapper_SpaceMouse
 * Method:    isDriverInstalled
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_rm_spacemousewrapper_SpaceMouse_isDriverInstalled
  (JNIEnv *, jclass);

/*
 * Class:     com_rm_spacemousewrapper_SpaceMouse
 * Method:    setConnexionHandlers
 * Signature: (Lcom/rm/spacemousewrapper/SpaceMouse;Z)I
 */
JNIEXPORT jint JNICALL Java_com_rm_spacemousewrapper_SpaceMouse_setConnexionHandlers
  (JNIEnv *, jclass, jobject, jboolean);

/*
 * Class:     com_rm_spacemousewrapper_SpaceMouse
 * Method:    registerConnexionClient
 * Signature: (ILjava/lang/String;IJ)I
 */
JNIEXPORT jint JNICALL Java_com_rm_spacemousewrapper_SpaceMouse_registerConnexionClient
  (JNIEnv *, jclass, jint, jstring, jint, jlong);

/*
 * Class:     com_rm_spacemousewrapper_SpaceMouse
 * Method:    setConnexionClientMask
 * Signature: (IJ)V
 */
JNIEXPORT void JNICALL Java_com_rm_spacemousewrapper_SpaceMouse_setConnexionClientMask
  (JNIEnv *, jclass, jint, jlong);

/*
 * Class:     com_rm_spacemousewrapper_SpaceMouse
 * Method:    unregisterConnexionClient
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_rm_spacemousewrapper_SpaceMouse_unregisterConnexionClient
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_rm_spacemousewrapper_SpaceMouse
 * Method:    cleanUpConnexionHandler
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_rm_spacemousewrapper_SpaceMouse_cleanUpConnexionHandler
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
